
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_INTERRUPTCONTROLLER_DEVICE_ID,
		XPAR_INTERRUPTCONTROLLER_BASEADDR,
		XPAR_INTERRUPTCONTROLLER_KIND_OF_INTR,
		XPAR_INTERRUPTCONTROLLER_HAS_FAST,
		XPAR_INTERRUPTCONTROLLER_IVAR_RESET_VALUE,
		XPAR_INTERRUPTCONTROLLER_NUM_INTR_INPUTS,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_INTERRUPTCONTROLLER_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			}
		}

	}
};

